project:
  type: website
  output-dir: docs


lang: en
website:
  title: "Mobility Flows and Accessibility Using R and Big Open Data"
  site-url: https://e-kotov.github.io/spanish-open-mobility-workshop-ic2s2-2025/
  repo-url: https://github.com/e-kotov/spanish-open-mobility-workshop-ic2s2-2025
  page-navigation: true
  page-footer: 
      border: true
      left: "Authors: Egor Kotov & Johannes Mast" 
      center:
        - text: "CC0 1.0"
          href: license.qmd
      right: 
        - icon: github
          href: https://github.com/e-kotov/spanish-open-mobility-workshop-ic2s2-2025

  sidebar:
    style: "docked"
    search: true
    tools: 
      - icon: github
        text: Github
        href: https://github.com/e-kotov/spanish-open-mobility-workshop-ic2s2-2025
    contents:
      - index.qmd



format:
  html:
    theme:
      light: zephyr
      dark: slate
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 4
    toc-location: right
    code-overflow: wrap
    grid:
      body-width: 800px
    mermaid:
      theme: neutral

bibliography: references.bib
bibliographystyle: apa

editor: source

editor_options:
  markdown:
    wrap: 72
    canonical: true

execute:
  freeze: auto
