project:
  type: website
  output-dir: docs

resources: 
  - media/*

lang: en
website:
  title: "Mobility Flows and Accessibility Using R and Big Open Data"
  site-url: https://e-kotov.github.io/spanish-open-mobility-workshop-ic2s2-2025/
  repo-url: https://github.com/e-kotov/spanish-open-mobility-workshop-ic2s2-2025
  open-graph:
    title: "Mobility Flows and Accessibility Using R and Big Open Data"
    image: media/card.png
    image-alt: "Workshop on Mobility Flows and Accessibility Using R and Big Open Data, IC2S2 2025 conference, Norrköping, Sweden, July 21, 2025. Tutors: Egor Kotov & Johannes Mast"
    description: "Workshop on Mobility Flows and Accessibility Using R and Big Open Data, IC2S2 2025 conference, Norrköping, Sweden, July 21, 2025. Tutors: Egor Kotov & Johannes Mast. This workshop will teach you how to use the R package spanishoddata to access open human mobility data and how to aggregate it with duckdb. We will also explore how to visualize mobility flows and accessibility using R package flowmapper and flowmapblue."
  page-navigation: true
  page-footer: 
      border: true
      left: "Authors: Egor Kotov & Johannes Mast" 
      center:
        - text: "CC-BY-SA 4.0"
          href: https://creativecommons.org/licenses/by-sa/4.0/
      right: 
        - icon: github
          href: https://github.com/e-kotov/spanish-open-mobility-workshop-ic2s2-2025

  sidebar:
    style: "docked"
    search: true
    tools: 
      - icon: github
        text: Github
        href: https://github.com/e-kotov/spanish-open-mobility-workshop-ic2s2-2025
    contents:
      - text: "👋 Workshop Introduction"
        href: index.qmd
      - text: "🛠️ Software Setup"
        href: 0-software-setup.qmd
      - text: "1a. 📽️ Slides: Getting and aggregating the data"
        href: 1-mobility-data-slides-container.qmd
      - text: "1b. 📊 Tutorial: Getting and aggregating the data"
        href: 1-mobility-data-tutorial.qmd
      - text: "2a. 📽️ Slides: Flows Visualisation"
        href: 2-flow-vis-slides-container.qmd
      - text: "2b. 📊 Tutorial: Flows Visualisation"
        href: 2-flow-vis-tutorial.qmd
      - text: "3a. 📽️ Slides: Accessibility vs Mobility"
        href: 3-accessibility-vs-mobility-slides-container.qmd
      - text: "3b. 📊 Tutorial: Accessibility vs Mobility"
        href: 3-accessibility-vs-mobility-tutorial.qmd




authors:
  - name: Egor Kotov
    url: https://www.ekotov.pro/
    orcid: 0000-0001-6690-5345
    affiliations:
      - ref: mpidr
      - ref: upf
  - name: Johannes Mast
    url: https://www.linkedin.com/in/johannes-mast-9bb53b219/
    orcid: 0000-0001-6595-5834
    affiliations:
      - ref: dlr
      - ref: jmu

affiliations:
  - id: mpidr
    name: Max Planck Institute for Demographic Research
    city: Rostock
    country: Germany
    url: https://www.demogr.mpg.de/en
  - id: upf
    name: Universitat Pompeu Fabra
    city: Barcelona
    country: Spain
    url: https://www.upf.edu/en/web/politiques/home
  - id: dlr
    name: The German Aerospace Center (Deutsches Zentrum für Luft- und Raumfahrt, DLR)
    city: Munich
    country: Germany
    url: https://www.dlr.de
  - id: jmu
    name: Julius-Maximilians-Universität Würzburg (JMU)
    city: Würzburg
    country: Germany
    url: https://www.uni-wuerzburg.de/en/


format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: 'ekotov\.pro'
    include-in-header:
      - text: |
          <!-- tell Zotero this is a webpage via Dublin Core -->
          <meta name="DC.Type" content="WebPage">
      - file: media/analytics.html
    theme:
      light: zephyr
      dark: slate
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 4
    toc-location: right
    code-overflow: wrap
    grid:
      body-width: 800px
    mermaid:
      theme: neutral

bibliography: references.bib
bibliographystyle: apa

citation:
  type: webpage
  title: "IC2S2 2025 Workshop: Mobility Flows and Accessibility Using R and Big Open Data"
  # url: https://www.ekotov.pro/spanish-open-mobility-workshop-ic2s2-2025/
  # container-title: "IC2S2 2025 Workshop: Mobility Flows and Accessibility Using R and Big Open Data"
  issued: 2025-07-21
  # doi: 10.5281/zenodo.15794849 # TODO
# doi: 10.5281/zenodo.15794849 # TODO
google-scholar: true

editor: source

editor_options:
  markdown:
    wrap: 72
    canonical: true

execute:
  eval: false
  freeze: false
  warning: false
  error: false
